version: '3.8'

services:
  frontend-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-service
    environment:
      - NODE_ENV=production
      - PORT=4000
      - API_BASE_URL=http://study-manager-service:8080
      - AUTH_BASE_URL=http://auth-service:8081
    ports:
      - "4000:4000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


