version: '3.8'

services:
  frontend-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-service
    environment:
      - NODE_ENV=development
      - PORT=4200
      - API_BASE_URL=http://study-manager-service:8080
      - AUTH_BASE_URL=http://auth-service:8081
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "4200:4200"
    volumes:
      # Volume para o código fonte - permite hot reload
      - .:/app
      # Volume para node_modules - evita conflitos
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4200"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


